/**
 * GitHub integration using gh CLI
 */

export interface CommentOptions {
  issueNumber: number;
  success: boolean;
  durationMs: number;
  inputTokens: number;
  outputTokens: number;
  totalCostUsd: number;
  prUrl: string | null;
  errorMessage: string | null;
  sessionId: string | null;
}

async function getRepoPath(): Promise<string> {
  const proc = Bun.spawn(["git", "remote", "get-url", "origin"], {
    stdout: "pipe",
    stderr: "pipe",
  });

  const output = await new Response(proc.stdout).text();
  const exitCode = await proc.exited;

  if (exitCode !== 0) {
    throw new Error("Failed to get git remote URL");
  }

  // Parse GitHub URL: git@github.com:owner/repo.git or https://github.com/owner/repo.git
  const url = output.trim();
  let match = url.match(/github\.com[:/]([^/]+\/[^/.]+)/);
  if (match?.[1]) {
    return match[1].replace(/\.git$/, "");
  }

  throw new Error(`Could not parse repo path from: ${url}`);
}

function formatDuration(ms: number): string {
  const seconds = Math.floor(ms / 1000);
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  
  if (minutes > 0) {
    return `${minutes}m ${remainingSeconds}s`;
  }
  return `${seconds}s`;
}

function formatCost(usd: number): string {
  return `$${usd.toFixed(4)}`;
}

export async function postIssueComment(options: CommentOptions): Promise<void> {
  const repo = await getRepoPath();
  const statusEmoji = options.success ? "✅" : "❌";
  const statusText = options.success ? "completed successfully" : "failed";

  let body = `<!-- KOTADB-AUTOMATION-BOT -->
## ${statusEmoji} Automation ${statusText}

| Metric | Value |
|--------|-------|
| Duration | ${formatDuration(options.durationMs)} |
| Input Tokens | ${options.inputTokens.toLocaleString()} |
| Output Tokens | ${options.outputTokens.toLocaleString()} |
| Cost | ${formatCost(options.totalCostUsd)} |
`;

  if (options.prUrl) {
    body += `| PR | ${options.prUrl} |\n`;
  }

  if (options.sessionId) {
    body += `| Session | \`${options.sessionId}\` |\n`;
  }

  if (options.errorMessage) {
    body += `\n### Error Details\n\n\`\`\`\n${options.errorMessage}\n\`\`\`\n`;
  }

  body += `\n---\n*Generated by KotaDB Automation*`;

  const proc = Bun.spawn(
    ["gh", "issue", "comment", String(options.issueNumber), "--repo", repo, "--body", body],
    {
      stdout: "pipe",
      stderr: "pipe",
    }
  );

  const exitCode = await proc.exited;

  if (exitCode !== 0) {
    const stderr = await new Response(proc.stderr).text();
    throw new Error(`Failed to post comment: ${stderr}`);
  }
}
