#!/usr/bin/env -S uv run
# /// script
# dependencies = ["python-dotenv", "pydantic"]
# ///

"""ADW plan & build orchestration for KotaDB."""

from __future__ import annotations

import logging
import os
import shutil
import sys
from typing import Optional, Tuple, Union

if __package__ is None or __package__ == "":
    import sys
    from pathlib import Path

    sys.path.append(str(Path(__file__).resolve().parent.parent))

from adws.agent import execute_template
from adws.data_types import (
    AgentPromptResponse,
    AgentTemplateRequest,
    GitHubIssue,
    IssueClassSlashCommand,
)
from adws.github import extract_repo_path, fetch_issue, get_repo_url, make_issue_comment
from adws.utils import load_adw_env, make_adw_id, setup_logger

# Agent labels mirror .claude command ownership.
AGENT_PLANNER = "sdlc_planner"
AGENT_IMPLEMENTOR = "sdlc_implementor"
AGENT_CLASSIFIER = "issue_classifier"
AGENT_PLAN_FINDER = "plan_finder"
AGENT_BRANCH_GENERATOR = "branch_generator"
AGENT_PR_CREATOR = "pr_creator"


def check_env_vars(logger: Optional[logging.Logger] = None) -> None:
    """Ensure critical environment variables and CLI prerequisites are present."""

    required = ["ANTHROPIC_API_KEY"]
    missing = [var for var in required if not os.getenv(var)]

    claude_path = (os.getenv("CLAUDE_CODE_PATH") or "claude").strip()
    if not shutil.which(claude_path):
        missing.append(f"CLAUDE_CODE_PATH (CLI not found at '{claude_path}')")

    if missing:
        message = "Missing required automation prerequisites:\n" + "\n".join(f"  - {item}" for item in missing)
        if logger:
            logger.error(message)
        else:
            print(message, file=sys.stderr)
        sys.exit(1)


def parse_args() -> Tuple[str, Optional[str]]:
    """Parse CLI arguments for issue number and optional run id."""

    if len(sys.argv) < 2:
        print("Usage: uv run adws/adw_plan_build.py <issue-number> [adw-id]", file=sys.stderr)
        sys.exit(1)
    issue_number = sys.argv[1]
    adw_id = sys.argv[2] if len(sys.argv) > 2 else None
    return issue_number, adw_id


def format_issue_message(adw_id: str, agent_name: str, message: str, session_id: Optional[str] = None) -> str:
    """Standardise issue comment messages with ADW tracking metadata."""

    prefix = f"{adw_id}_{agent_name}"
    if session_id:
        prefix = f"{prefix}_{session_id}"
    return f"{prefix}: {message}"


def classify_issue(issue: GitHubIssue, adw_id: str, logger: logging.Logger) -> Tuple[Optional[IssueClassSlashCommand], Optional[str]]:
    """Ask the classifier agent for a slash command classification."""

    request = AgentTemplateRequest(
        agent_name=AGENT_CLASSIFIER,
        slash_command="/classify_issue",
        args=[issue.model_dump_json(indent=2, by_alias=True)],
        adw_id=adw_id,
        model="sonnet",
    )
    logger.debug(f"classify_issue request: {request.model_dump_json(indent=2, by_alias=True)}")
    response = execute_template(request)
    logger.debug(f"classify_issue response: {response.model_dump_json(indent=2)}")

    if not response.success:
        return None, response.output

    command = response.output.strip()
    if command == "0":
        return None, "No classification produced"
    if command not in {"/chore", "/bug", "/feature"}:
        return None, f"Unrecognised classification: {command}"
    return command, None  # type: ignore[return-value]


def build_plan(issue: GitHubIssue, command: str, adw_id: str, logger: logging.Logger) -> AgentPromptResponse:
    """Generate an implementation plan using the planner agent."""

    request = AgentTemplateRequest(
        agent_name=AGENT_PLANNER,
        slash_command=command,
        args=[f"{issue.title}: {issue.body}"],
        adw_id=adw_id,
        model="sonnet",
    )
    logger.debug(f"build_plan request: {request.model_dump_json(indent=2, by_alias=True)}")
    response = execute_template(request)
    logger.debug(f"build_plan response: {response.model_dump_json(indent=2)}")
    return response


def get_plan_file(plan_output: str, adw_id: str, logger: logging.Logger) -> Tuple[Optional[str], Optional[str]]:
    """Locate the plan file generated by the planner agent."""

    request = AgentTemplateRequest(
        agent_name=AGENT_PLAN_FINDER,
        slash_command="/find_plan_file",
        args=[plan_output],
        adw_id=adw_id,
        model="sonnet",
    )
    response = execute_template(request)
    if not response.success:
        return None, response.output

    plan_path = response.output.strip()
    if plan_path == "0":
        return None, "No plan file located"
    if "/" not in plan_path:
        return None, f"Invalid plan path returned: {plan_path}"
    logger.debug(f"plan file located: {plan_path}")
    return plan_path, None


def implement_plan(plan_file: str, adw_id: str, logger: logging.Logger) -> AgentPromptResponse:
    """Run the implementor agent against the generated plan."""

    request = AgentTemplateRequest(
        agent_name=AGENT_IMPLEMENTOR,
        slash_command="/implement",
        args=[plan_file],
        adw_id=adw_id,
        model="sonnet",
    )
    logger.debug(f"implement_plan request: {request.model_dump_json(indent=2, by_alias=True)}")
    response = execute_template(request)
    logger.debug(f"implement_plan response: {response.model_dump_json(indent=2)}")
    return response


def git_branch(
    issue: GitHubIssue,
    issue_class: IssueClassSlashCommand,
    adw_id: str,
    logger: logging.Logger,
) -> Tuple[Optional[str], Optional[str]]:
    """Create a new branch for the issue."""

    issue_type = issue_class.replace("/", "")
    request = AgentTemplateRequest(
        agent_name=AGENT_BRANCH_GENERATOR,
        slash_command="/generate_branch_name",
        args=[issue_type, adw_id, issue.model_dump_json(by_alias=True)],
        adw_id=adw_id,
        model="sonnet",
    )
    response = execute_template(request)
    if not response.success:
        return None, response.output
    branch_name = response.output.strip()
    logger.info(f"Created branch: {branch_name}")
    return branch_name, None


def git_commit(
    agent_name: str,
    issue: GitHubIssue,
    issue_class: IssueClassSlashCommand,
    adw_id: str,
    logger: logging.Logger,
) -> Tuple[Optional[str], Optional[str]]:
    """Create a git commit with a CLAUDE-generated message."""

    issue_type = issue_class.replace("/", "")
    request = AgentTemplateRequest(
        agent_name=f"{agent_name}_committer",
        slash_command="/commit",
        args=[agent_name, issue_type, issue.model_dump_json(by_alias=True)],
        adw_id=adw_id,
        model="sonnet",
    )
    response = execute_template(request)
    if not response.success:
        return None, response.output
    commit_message = response.output.strip()
    logger.info(f"Created commit: {commit_message}")
    return commit_message, None


def pull_request(
    branch_name: str,
    issue: GitHubIssue,
    plan_file: str,
    adw_id: str,
    logger: logging.Logger,
) -> Tuple[Optional[str], Optional[str]]:
    """Open a pull request summarising the work."""

    request = AgentTemplateRequest(
        agent_name=AGENT_PR_CREATOR,
        slash_command="/pull_request",
        args=[branch_name, issue.model_dump_json(by_alias=True), plan_file, adw_id],
        adw_id=adw_id,
        model="sonnet",
    )
    response = execute_template(request)
    if not response.success:
        return None, response.output
    pr_url = response.output.strip()
    logger.info(f"Created pull request: {pr_url}")
    return pr_url, None


def check_error(
    result: Union[Optional[str], AgentPromptResponse],
    issue_number: str,
    adw_id: str,
    agent_name: str,
    prefix: str,
    logger: logging.Logger,
) -> None:
    """Normalize error handling and propagate context to GitHub."""

    error: Optional[str]
    if isinstance(result, AgentPromptResponse):
        error = None if result.success else result.output
    else:
        error = result

    if error:
        logger.error(f"{prefix}: {error}")
        make_issue_comment(issue_number, format_issue_message(adw_id, agent_name, f"❌ {prefix}: {error}"))
        sys.exit(1)


def main() -> None:
    """Entry point for orchestrating a single GitHub issue."""

    load_adw_env()
    issue_number, adw_id = parse_args()
    adw_id = adw_id or make_adw_id()
    logger = setup_logger(adw_id, "adw_plan_build")
    logger.info(f"ADW ID: {adw_id}")

    check_env_vars(logger)

    try:
        repo_url = get_repo_url()
        repo_path = extract_repo_path(repo_url)
    except ValueError as exc:
        logger.error(f"Error resolving repository: {exc}")
        sys.exit(1)

    issue = fetch_issue(issue_number, repo_path)
    logger.debug(issue.model_dump_json(indent=2, by_alias=True))
    make_issue_comment(issue_number, format_issue_message(adw_id, "ops", "✅ Starting ADW workflow"))

    issue_command, error = classify_issue(issue, adw_id, logger)
    check_error(error, issue_number, adw_id, "ops", "Error classifying issue", logger)
    assert issue_command  # for type-checkers
    logger.info(f"Issue classified as {issue_command}")
    make_issue_comment(issue_number, format_issue_message(adw_id, "ops", f"✅ Issue classified as: {issue_command}"))

    branch_name, error = git_branch(issue, issue_command, adw_id, logger)
    check_error(error, issue_number, adw_id, "ops", "Error creating branch", logger)
    assert branch_name
    make_issue_comment(issue_number, format_issue_message(adw_id, "ops", f"✅ Working on branch: {branch_name}"))

    plan_response = build_plan(issue, issue_command, adw_id, logger)
    check_error(plan_response, issue_number, adw_id, AGENT_PLANNER, "Error building plan", logger)
    make_issue_comment(issue_number, format_issue_message(adw_id, AGENT_PLANNER, "✅ Implementation plan created"))

    plan_file, error = get_plan_file(plan_response.output, adw_id, logger)
    check_error(error, issue_number, adw_id, "ops", "Error locating plan file", logger)
    assert plan_file
    make_issue_comment(issue_number, format_issue_message(adw_id, "ops", f"✅ Plan file created: {plan_file}"))

    commit_message, error = git_commit(AGENT_PLANNER, issue, issue_command, adw_id, logger)
    check_error(error, issue_number, adw_id, AGENT_PLANNER, "Error committing plan", logger)
    logger.debug(f"Plan commit: {commit_message}")

    implement_response = implement_plan(plan_file, adw_id, logger)
    check_error(implement_response, issue_number, adw_id, AGENT_IMPLEMENTOR, "Error implementing plan", logger)
    make_issue_comment(issue_number, format_issue_message(adw_id, AGENT_IMPLEMENTOR, "✅ Solution implemented"))

    commit_message, error = git_commit(AGENT_IMPLEMENTOR, issue, issue_command, adw_id, logger)
    check_error(error, issue_number, adw_id, AGENT_IMPLEMENTOR, "Error committing implementation", logger)
    logger.debug(f"Implementation commit: {commit_message}")

    pr_url, error = pull_request(branch_name, issue, plan_file, adw_id, logger)
    check_error(error, issue_number, adw_id, "ops", "Error creating pull request", logger)
    make_issue_comment(issue_number, format_issue_message(adw_id, "ops", f"✅ Pull request created: {pr_url}"))

    make_issue_comment(issue_number, format_issue_message(adw_id, "ops", "✅ ADW workflow completed successfully"))
    logger.info(f"Workflow completed for issue #{issue_number}")


if __name__ == "__main__":
    main()
