name: Feature Request
description: Propose a new feature or enhancement
title: "feat: "
labels: ["enhancement", "status:needs-investigation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and this feature hasn't been requested before
          required: true
        - label: This feature aligns with KotaDB's goal as a local-only code intelligence tool
          required: true
        - label: I agree to follow the project's Code of Conduct
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature or capability do you want to add?
      placeholder: A clear description of the feature...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: This feature would help...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context (Optional)
      description: Any other context, screenshots, or examples
      placeholder: Additional details...
    validations:
      required: false
